version: "1"
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - delivery-route-optimisation-app

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9093:9093'          #change to 9093 to access external from your windows host
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT     #add aditional listener for external
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093                              #9092 will be for other containers, 9093 for your windows client
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093     #9092 will be for other containers, 9093 for your windows client
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper
    networks:
      - delivery-route-optimisation-app

  spark:
    image: 'mypyspark-notebook-spark-2:03'
    # command run directly in a dockerfile, to build the custome image mypyspark-notebook-spark-2:01
    #command: sudo wget https://jdbc.postgresql.org/download/postgresql-42.2.5.jar -P /usr/local/spark-2.4.5-bin-hadoop2.7/jars
    ports:
      - '8888:8888'
      - "4040-4080:4040-4080"
    volumes:
      - ./spark/:/home/jovyan/work
      - ./app/postgresql/:/home/jovyan/work/modules/postgresql
    environment:
      - WINDOWS_HOST
      - PGDATABASE
      - PGUSER
      - PGPASSWORD
    networks:
      - delivery-route-optimisation-app
  app:
    environment:
      - WINDOWS_HOST
      - PGDATABASE
      - PGUSER
      - PGPASSWORD
    image: 'app-optiway:05'
    ports:
       - '80:80'
    volumes:
      - ./app:/app
    networks:
      - delivery-route-optimisation-app

networks:
  delivery-route-optimisation-app:
    driver: bridge